server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # forward API calls to the backend container
location /api/ {
    proxy_pass https://book-recommender-production-30b5.up.railway.app/api/;
    proxy_set_header Host book-recommender-production-30b5.up.railway.app;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_ssl_server_name on;
}

    location = /favicon.svg {
        access_log off;
    }
}
